python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-20dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-21dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-22dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-23dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-24dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-25dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-26dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-27dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-28dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/CBF/-29dB/ --truth truth.mat --single 1 --threshold 2