python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-20dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-21dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-22dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-23dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-24dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-25dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-26dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-27dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-28dB/ --truth truth.mat --single 1 --threshold 2
python calculatetrace.py --input /wangyunhao/cds/wangyunhao/data/BTR/mmsegform/test/512/lognorm_frame/New202502/SNR/Match/-29dB/ --truth truth.mat --single 1 --threshold 2