# model settings
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='SUNetV2',
        img_size=512,
        patch_size=4,
        in_chans=3,
        out_chans=256,
        embed_dim=96,
        depths=[2, 2, 18, 2],
        num_heads=[4, 8, 16, 32],
        window_size=8,
        mlp_ratio=4.,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.1,
        ape=False,
        patch_norm=True,
        out_indices=[0, 1, 2, 3],
        frozen_stages=-1,
        use_checkpoint=False,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='PReLU'),
        upsample_cfg=dict(mode='nearest'),
        feature_strides=[4, 8, 16, 32]),
    decode_head=dict(
        type='FCNHead',
        in_channels=128,
        in_index=-1,
        channels=128,
        kernel_size=3,
        num_convs=0,
        concat_input=False,
        dropout_ratio=-1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
